
// src/lib/crossword-puzzles.ts
import type { Difficulty } from './constants';

export interface CrosswordWord {
  clue: string;
  answer: string;
  direction: 'across' | 'down';
  row: number;
  col: number;
}

export interface CrosswordPuzzle {
  id: string;
  difficulty: Difficulty;
  gridSize: number;
  words: CrosswordWord[];
}

// This file is now deprecated and will be removed.
// Puzzles are generated by AI in generate-crossword-flow.ts
export const CROSSWORD_PUZZLES: CrosswordPuzzle[] = [];
